//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes()
        {
            this.DetallesOrdenes = new HashSet<DetallesOrdenes>();
        }
    
        public int IdOrden { get; set; }
        public int IdUsuario { get; set; }
        public int IdEnvio { get; set; }
        public int IdPago { get; set; }
        public int IdNoConcretadas { get; set; }
        public Nullable<System.DateTime> FechaOrden { get; set; }
        public System.DateTime TiempoExpiracion { get; set; }
        public string Estado { get; set; }
        public decimal Saldo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesOrdenes> DetallesOrdenes { get; set; }
        public virtual FormasEnvio FormasEnvio { get; set; }
        public virtual FormasPago FormasPago { get; set; }
        public virtual OrdenesNoConcretadas OrdenesNoConcretadas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
